import json
import os

def detect_forbidden_primitives():
    results = {
        "mt_law_a_primitive_detection_validation": {
            "status": "pass",
            "checks": [],
            "warnings": [],
            "errors": []
        }
    }
    
    report = results["mt_law_a_primitive_detection_validation"]
    
    # Files to scan
    targets = [
        "docs/math/mt_law_a_bounded_continuation_persistence_definition.md",
        "docs/math/mt_law_a_counterexample_obligations.md",
        "docs/math/mt_law_a_validator_depth_upgrade.md"
    ]
    
    forbidden = [
        "absolute persistence", "primitive spacetime", "intrinsic geometry",
        "observer-independent", "unbounded continuation", "perfect identity"
    ]
    
    required = [
        "projectional", "bounded", "admissibility-constrained",
        "failure-preserving", "reconstruction-limited"
    ]
    
    for path in targets:
        if not os.path.exists(path):
            continue
            
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read().lower()
            
            # Check for forbidden patterns
            for pattern in forbidden:
                if pattern in content:
                    # Check if it is negated or in a clause like "no absolute persistence"
                    if f"no {pattern}" not in content and f"block {pattern}" not in content:
                        report["status"] = "fail"
                        report["errors"].append(f"Forbidden primitive pattern '{pattern}' found in {path}")
            
            # Check for required terminology
            for term in required:
                if term not in content:
                    report["warnings"].append(f"Recommended terminology '{term}' missing in {path}")

    report["checks"].append("Scan for forbidden primitive ontology and physical overclaims complete.")
    
    # Update the result file generated by the semantic script
    result_path = "validation/results/mt_law_a_semantic_integrity_result.json"
    if os.path.exists(result_path):
        try:
            with open(result_path, 'r') as f:
                data = json.load(f)
            
            data["primitive_violations"] = report["errors"]
            if report["status"] == "fail":
                data["validation_status"] = "fail"
                
            with open(result_path, 'w') as f:
                json.dump(data, f, indent=2)
        except:
            pass

    return results

if __name__ == "__main__":
    res = detect_forbidden_primitives()
    print(json.dumps(res, indent=2))
