import json
import os
from datetime import datetime

def validate_consistency_audit():
    registry_path = "registry/math/restricted_local_proof_consistency_audit_registry.json"
    doc_path = "docs/math/restricted_local_proof_consistency_audit.md"
    result_path = "validation/results/restricted_local_proof_consistency_audit_result.json"
    summary_path = "validation/results/restricted_local_proof_consistency_audit_summary.json"
    
    report = {
        "validation_id": "VAL-RLP-CONS-VALID-001",
        "status": "pass",
        "audit_targets_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing consistency audit registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing consistency audit document")

    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["audit_targets_verified"] = len(registry["audit_targets"])
        
        # Check for NOT_PROVEN status
        if registry["governance"]["theorem_status"] != "NOT_PROVEN":
            report["status"] = "fail"
            report["governance_violations"].append("forbidden theorem status promotion in consistency audit")

    # Check for summary existence (generated by runner)
    if not os.path.exists(summary_path):
         report["status"] = "warning"
         report["governance_violations"].append("consistency audit summary not yet generated by runner")

    # Check doc for mandatory targets
    expected_targets = [
        "operator type consistency",
        "restricted scope preservation",
        "failure geometry integrity"
    ]
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        for target in expected_targets:
            if target not in content:
                report["status"] = "fail"
                report["governance_violations"].append(f"missing mandatory audit target: {target}")

    # Final result
    with open(result_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_consistency_audit()
    print(json.dumps(res, indent=2))
