import json
import os
from datetime import datetime

def validate_stability_consolidation():
    registry_path = "registry/math/restricted_local_stability_consolidation_registry.json"
    doc_path = "docs/math/restricted_local_stability_consolidation.md"
    result_path = "validation/results/restricted_local_stability_consolidation_result.json"
    summary_path = "validation/results/restricted_local_stability_consolidation_summary.json"
    
    report = {
        "validation_id": "VAL-RLSC-VALID-001",
        "status": "pass",
        "consolidation_targets_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing consolidation registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing consolidation document")

    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["consolidation_targets_verified"] = len(registry["consolidation_targets"])
        
        # MANDATE: Check that no consolidation class allows theorem promotion
        for cls in registry["consolidation_classes"]:
            if cls["promotion_allowed"] is True:
                 report["status"] = "fail"
                 report["governance_violations"].append(f"forbidden promotion authorization in class {cls['class_id']}")
        
        # Check for NOT_PROVEN status
        if registry["governance"]["theorem_status"] != "NOT_PROVEN":
            report["status"] = "fail"
            report["governance_violations"].append("forbidden theorem status promotion in consolidation registry")

    # Check for summary existence (generated by runner)
    if not os.path.exists(summary_path):
         report["status"] = "warning"
         report["governance_violations"].append("stability consolidation summary not yet generated by runner")

    # Check doc for mandatory blocks
    expected_decls = [
        "not_proven",
        "strictly_local_restricted_domain",
        "non-collapse"
    ]
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        for decl in expected_decls:
            if decl not in content:
                report["status"] = "fail"
                report["governance_violations"].append(f"missing mandatory declaration: {decl}")

    # Final result
    with open(result_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_stability_consolidation()
    print(json.dumps(res, indent=2))
