import json
import os
from datetime import datetime

def validate_sim_harness():
    registry_path = "registry/math/mpf_sim_001_registry.json"
    doc_path = "docs/math/mpf_sim_001_pi_a_stability.md"
    result_path = "validation/results/mpf_sim_001_results.json"
    val_out_path = "validation/results/mpf_sim_001_validation_result.json"
    
    report = {
        "validation_id": "VAL-SIM-001-VALID",
        "status": "pass",
        "governance_violations": [],
        "metrics_found": [],
        "timestamp": datetime.now().isoformat()
    }
    
    # 1. Registry & Doc Existence
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing sim registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing sim documentation")

    # 2. Result Verification
    if not os.path.exists(result_path):
         report["status"] = "warning"
         report["governance_violations"].append("simulation results not yet generated by runner")
    else:
        with open(result_path, 'r') as f:
            data = json.load(f)
            
            # Check for governance headers
            if data.get("status") != "NON_PHYSICAL_ANALOG_MODEL":
                 report["status"] = "fail"
                 report["governance_violations"].append("missing physics_status non-physical declaration in results")
            
            if data.get("theorem_status") != "NOT_PROVEN":
                 report["status"] = "fail"
                 report["governance_violations"].append("forbidden theorem status promotion in results")

            # Check for required metrics in scenarios
            if not data.get("scenarios"):
                 report["status"] = "fail"
                 report["governance_violations"].append("no simulation scenarios found in results")
            else:
                 required_keys = ["basin_class", "idempotence_error", "failure_geometry_triggered"]
                 for key in required_keys:
                     if key in data["scenarios"][0]:
                          report["metrics_found"].append(key)
                     else:
                          report["status"] = "fail"
                          report["governance_violations"].append(f"missing metric {key} in simulation results")

    # 3. Doc Content Verification
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        if "not_proven" not in content or "non_physical_analog_model" not in content:
             report["status"] = "fail"
             report["governance_violations"].append("missing governance footer in documentation")

    with open(val_out_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_sim_harness()
    print(json.dumps(res, indent=2))
