import json
import os
from datetime import datetime

def validate_review():
    registry_path = "registry/math/ts4_restricted_local_review_registry.json"
    doc_path = "docs/math/ts4_restricted_local_review.md"
    result_path = "validation/results/ts4_restricted_local_review_result.json"
    summary_path = "validation/results/ts4_restricted_local_review_summary.json"
    
    report = {
        "validation_id": "VAL-TS4-RLR-VALID-001",
        "status": "pass",
        "review_targets_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing review registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing review document")

    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["review_targets_verified"] = len(registry["review_targets"])
        
        # MANDATE: Check that no decision allows theorem promotion
        for dec in registry["review_decision_classes"]:
            if dec["promotion_allowed"] is True:
                 report["status"] = "fail"
                 report["governance_violations"].append(f"forbidden promotion authorization in decision {dec['decision_id']}")
        
        # Check for NOT_PROVEN status
        if registry["governance"]["theorem_status"] != "NOT_PROVEN":
            report["status"] = "fail"
            report["governance_violations"].append("forbidden theorem status promotion in review registry")

    # Check for summary existence (generated by runner)
    if not os.path.exists(summary_path):
         report["status"] = "warning"
         report["governance_violations"].append("review summary not yet generated by runner")

    # Check doc for mandatory blocks and scope
    expected_decls = [
        "not_proven",
        "strictly_local_restricted_domain",
        "pass-with-blockers"
    ]
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        for decl in expected_decls:
            if decl not in content:
                report["status"] = "fail"
                report["governance_violations"].append(f"missing mandatory declaration: {decl}")

    # Final result
    with open(result_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_review()
    print(json.dumps(res, indent=2))
