import json
import os
from datetime import datetime

def validate_readiness_audit():
    registry_path = "registry/math/local_theorem_readiness_audit_registry.json"
    doc_path = "docs/math/local_theorem_readiness_audit.md"
    result_path = "validation/results/local_theorem_readiness_audit_result.json"
    summary_path = "validation/results/local_theorem_readiness_audit_summary.json"
    
    report = {
        "validation_id": "VAL-LTRA-VALID-001",
        "status": "pass",
        "readiness_checks_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing readiness audit registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing readiness audit document")

    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["readiness_checks_verified"] = len(registry["readiness_checks"])
        
        # Check for NOT_PROVEN status
        if registry["governance"]["theorem_status"] != "NOT_PROVEN":
            report["status"] = "fail"
            report["governance_violations"].append("forbidden theorem status promotion in readiness registry")

    # Check for summary existence (generated by runner)
    if not os.path.exists(summary_path):
         report["status"] = "warning"
         report["governance_violations"].append("readiness audit summary not yet generated by runner")

    # Check doc for mandatory blocks
    expected_decls = [
        "not_proven",
        "strictly_local_restricted_domain",
        "review only"
    ]
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        for decl in expected_decls:
            if decl not in content:
                report["status"] = "fail"
                report["governance_violations"].append(f"missing mandatory declaration: {decl}")

    # Final result
    with open(result_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_readiness_audit()
    print(json.dumps(res, indent=2))
