import json
import os
from datetime import datetime

def validate_reconciliation():
    registry_path = "registry/math/ts4_stability_reconciliation_registry.json"
    doc_path = "docs/math/ts4_stability_reconciliation.md"
    result_path = "validation/results/ts4_stability_reconciliation_result.json"
    summary_path = "validation/results/ts4_stability_reconciliation_summary.json"
    
    report = {
        "validation_id": "VAL-TS4-SR-VALID-001",
        "status": "pass",
        "reconciliation_targets_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing reconciliation registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing reconciliation document")

    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["reconciliation_targets_verified"] = len(registry["reconciliation_targets"])
        
        # MANDATE: Check that no reconciliation class allows theorem promotion
        for cls in registry["reconciliation_classes"]:
            if cls["promotion_allowed"] is True:
                 report["status"] = "fail"
                 report["governance_violations"].append(f"forbidden promotion authorization in class {cls['class_id']}")
        
        # Check for NOT_PROVEN status
        if registry["governance"]["theorem_status"] != "NOT_PROVEN":
            report["status"] = "fail"
            report["governance_violations"].append("forbidden theorem status promotion in reconciliation registry")

    # Check for summary existence (generated by runner)
    if not os.path.exists(summary_path):
         report["status"] = "warning"
         report["governance_violations"].append("reconciliation summary not yet generated by runner")

    # Check doc for mandatory blocks and scope
    expected_decls = [
        "not_proven",
        "strictly_local_restricted_domain",
        "failure geometry remains active"
    ]
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        for decl in expected_decls:
            if decl not in content:
                report["status"] = "fail"
                report["governance_violations"].append(f"missing mandatory declaration: {decl}")

    # Final result
    with open(result_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_reconciliation()
    print(json.dumps(res, indent=2))
