import json
import os
from datetime import datetime

def validate_whole_relation_flattening_risk_audit():
    registry_path = "registry/math/whole_relation_flattening_risk_audit_registry.json"
    result_path = "validation/results/whole_relation_flattening_risk_audit_validation_result.json"
    audit_result_path = "validation/results/whole_relation_flattening_risk_audit_result.json"
    
    report = {
        "validation_id": "VAL-WRF-VAL-001",
        "status": "pass",
        "categories_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("audit registry missing")
        return report

    with open(registry_path, 'r', encoding='utf-8') as f:
        registry = json.load(f)
        
    # 1. Audit Status Check
    if registry.get("audit_status") != "CANDIDATE_RISK_AUDIT":
        report["status"] = "fail"
        report["governance_violations"].append("illegal audit status in registry")
    
    # 2. Risk Category Verification
    risk_categories = registry.get("risk_categories", [])
    required_risks = ["WRF-001", "WRF-002", "WRF-003", "WRF-004", "WRF-005", "WRF-006", "WRF-007"]
    registered_risks = [r["risk_id"] for r in risk_categories]
    for rr in required_risks:
        if rr not in registered_risks:
            report["status"] = "fail"
            report["governance_violations"].append(f"required risk category missing: {rr}")
        else:
            report["categories_verified"] += 1

    # 3. Flag Pattern Verification
    flag_patterns = registry.get("flag_patterns", {})
    for rc in risk_categories:
        if rc["name"] not in flag_patterns:
            report["status"] = "fail"
            report["governance_violations"].append(f"missing flag patterns for risk category: {rc['name']}")

    # 4. Result Verification
    if os.path.exists(audit_result_path):
        with open(audit_result_path, 'r', encoding='utf-8') as f:
            audit_data = json.load(f)
            if "overall_status" not in audit_data:
                 report["status"] = "fail"
                 report["governance_violations"].append("invalid audit result format: overall_status missing")
    else:
         report["status"] = "warning"
         report["governance_violations"].append("audit results not yet generated by runner")

    # 5. Governance Status Invariants
    gov = registry.get("governance_status", {})
    if gov.get("physics_status") != "NON_PHYSICAL_ANALOG_MODEL":
        report["status"] = "fail"
        report["governance_violations"].append("physics status must be NON_PHYSICAL_ANALOG_MODEL")
    if gov.get("theorem_status") != "NOT_PROVEN":
        report["status"] = "fail"
        report["governance_violations"].append("forbidden theorem status escalation")

    with open(result_path, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_whole_relation_flattening_risk_audit()
    print(json.dumps(res, indent=2))
