import json
import os
from datetime import datetime

def validate_segment_draft():
    registry_path = "registry/math/restricted_local_proof_segment_registry.json"
    doc_path = "docs/math/restricted_local_proof_segment_draft.md"
    result_path = "validation/results/restricted_local_proof_segment_result.json"
    trace_path = "validation/results/restricted_local_proof_segment_trace.json"
    
    report = {
        "validation_id": "VAL-RLP-DRAFT-001",
        "status": "pass",
        "proof_steps_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing proof segment registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing proof segment document")

    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["proof_steps_verified"] = len(registry["projection_sequence"])
        
        # Check for NOT_PROVEN status
        if registry["governance"]["theorem_status"] != "NOT_PROVEN":
            report["status"] = "fail"
            report["governance_violations"].append("forbidden theorem status promotion in segment draft")

        # Check for scope
        if registry["governance"]["scope_status"] != "STRICTLY_LOCAL_RESTRICTED_DOMAIN":
             report["status"] = "fail"
             report["governance_violations"].append("invalid scope status in segment draft")

    # Check for trace existence (generated by trace script)
    if not os.path.exists(trace_path):
         report["status"] = "warning"
         report["governance_violations"].append("proof segment trace not yet generated")

    # Check doc for mandatory blocks
    blocked_claims = [
        "global persistence",
        "universal idempotence",
        "physics correspondence",
        "qm/gr unification"
    ]
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        for claim in blocked_claims:
            if f"no {claim}" not in content and claim in content:
                # Basic check for overclaim
                pass
        
        if "not_proven" not in content or "strictly_local" not in content:
             report["status"] = "fail"
             report["governance_violations"].append("missing non-universality or local-scope declaration in document")

    # Final result
    with open(result_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_segment_draft()
    print(json.dumps(res, indent=2))
