import json
import os
from datetime import datetime

def validate_basin_classification():
    registry_path = "registry/math/recursive_stability_basin_classification_registry.json"
    doc_path = "docs/math/recursive_stability_basin_classification.md"
    result_path = "validation/results/recursive_stability_basin_classification_result.json"
    summary_path = "validation/results/recursive_stability_basin_classification_summary.json"
    
    report = {
        "validation_id": "VAL-LTC-BASIN-001",
        "status": "pass",
        "basin_classes_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing classification registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing classification document")

    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["basin_classes_verified"] = len(registry["basin_classes"])
        
        # Check for NOT_PROVEN status
        if registry["governance"]["theorem_status"] != "NOT_PROVEN":
            report["status"] = "fail"
            report["governance_violations"].append("forbidden theorem status promotion in classification")

    # Check for summary existence (generated by runner)
    if not os.path.exists(summary_path):
         report["status"] = "warning"
         report["governance_violations"].append("classification summary not yet generated by runner")

    # Check doc for forbidden claims
    forbidden_claims = ["proven", "global closure", "physical stability"]
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        if "status**: **proven**" in content:
             report["status"] = "fail"
             report["governance_violations"].append("forbidden 'proven' status in document")

    # Final result
    with open(result_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_basin_classification()
    print(json.dumps(res, indent=2))
