import json
import os
from datetime import datetime

def validate_drift_framework():
    registry_path = "registry/math/recursive_governance_drift_registry.json"
    doc_path = "docs/math/recursive_governance_drift_audit.md"
    result_path = "validation/results/recursive_governance_drift_audit_result.json"
    val_out_path = "validation/results/recursive_governance_drift_validation_result.json"
    
    report = {
        "validation_id": "VAL-RGD-FRAME-VALID-001",
        "status": "pass",
        "drift_classes_verified": 0,
        "protected_objects_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    # 1. Existence Checks
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing drift registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing drift documentation")

    # 2. Registry Verification
    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["drift_classes_verified"] = len(registry["drift_classes"])
        report["protected_objects_verified"] = len(registry["protected_boundary_objects"])
        
        # Check for mandatory invariants
        invariants = registry["governance_invariants"]
        if "NOT_PROVEN" not in invariants or "STRICTLY_LOCAL_RESTRICTED_DOMAIN" not in invariants:
            report["status"] = "fail"
            report["governance_violations"].append("missing core governance invariants in registry")

    # 3. Result Verification
    if not os.path.exists(result_path):
         report["status"] = "warning"
         report["governance_violations"].append("drift audit results not yet generated by runner")
    else:
        with open(result_path, 'r') as f:
            data = json.load(f)
            if "severity_score" not in data:
                 report["status"] = "fail"
                 report["governance_violations"].append("invalid audit result format: severity_score missing")

    # 4. Doc Content Verification
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        mandatory_terms = ["not_proven", "strictly_local_restricted_domain", "gdsi", "incompleteness preservation"]
        for term in mandatory_terms:
            if term not in content:
                report["status"] = "fail"
                report["governance_violations"].append(f"missing mandatory governance term '{term}' in documentation")

    # 5. Protected Object Verification (LAW034)
    found_law034 = False
    with open(registry_path, 'r') as f:
        registry = json.load(f)
        for obj in registry["protected_boundary_objects"]:
            if obj["object_id"] == "LAW034":
                found_law034 = True
                break
    if not found_law034:
        report["status"] = "fail"
        report["governance_violations"].append("LAW034 not listed as protected boundary object")

    with open(val_out_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_drift_framework()
    print(json.dumps(res, indent=2))
