import json
import os
from datetime import datetime

def validate_failure_geometry():
    registry_path = "registry/math/containment_failure_geometry_registry.json"
    result_path = "validation/results/containment_failure_geometry_map.json"
    val_out_path = "validation/results/containment_failure_geometry_validation_result.json"
    
    report = {
        "validation_id": "VAL-CFG-REG-VALID-001",
        "status": "pass",
        "geometries_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing geometry registry")
        return report

    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["geometries_verified"] = len(registry["failure_geometries"])
        
        # Check for mandatory escalation rules
        if not registry.get("escalation_rules") or not registry["escalation_rules"].get("mandatory_responses"):
             report["status"] = "fail"
             report["governance_violations"].append("missing mandatory escalation responses in registry")

    if not os.path.exists(result_path):
         report["status"] = "warning"
         report["governance_violations"].append("geometry audit map not yet generated by runner")

    with open(val_out_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_failure_geometry()
    print(json.dumps(res, indent=2))
