import json
import os
from datetime import datetime

def validate_eligibility_filter():
    registry_path = "registry/math/stable_basin_proof_eligibility_registry.json"
    doc_path = "docs/math/stable_basin_proof_eligibility_filter.md"
    result_path = "validation/results/stable_basin_proof_eligibility_filter_result.json"
    summary_path = "validation/results/stable_basin_proof_eligibility_summary.json"
    
    report = {
        "validation_id": "VAL-LTC-ELIG-001",
        "status": "pass",
        "output_classes_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing eligibility registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing eligibility document")

    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["output_classes_verified"] = len(registry["output_classes"])
        
        # MANDATE: Check that no output class allows theorem promotion
        for cls in registry["output_classes"]:
            if cls["promotion_allowed"] is True:
                 report["status"] = "fail"
                 report["governance_violations"].append(f"forbidden promotion authorization in class {cls['class_id']}")
        
        # Check for NOT_PROVEN status
        if registry["governance"]["theorem_status"] != "NOT_PROVEN":
            report["status"] = "fail"
            report["governance_violations"].append("forbidden theorem status promotion in eligibility filter")

    # Check for summary existence (generated by runner)
    if not os.path.exists(summary_path):
         report["status"] = "warning"
         report["governance_violations"].append("eligibility summary not yet generated by runner")

    # Check doc for mandatory declarations
    expected_decls = [
        "eligible for restricted local proof-step use only",
        "promotion blocked",
        "strictly_local_restricted_domain"
    ]
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        for decl in expected_decls:
            if decl not in content:
                report["status"] = "fail"
                report["governance_violations"].append(f"missing mandatory declaration: {decl}")

    # Final result
    with open(result_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_eligibility_filter()
    print(json.dumps(res, indent=2))
