import json
import os
from datetime import datetime

def validate_containment_framework():
    registry_path = "registry/math/recursive_containment_stress_registry.json"
    doc_path = "docs/math/recursive_containment_stress_framework.md"
    result_path = "validation/results/recursive_containment_stress_results.json"
    val_out_path = "validation/results/recursive_containment_validation_result.json"
    
    report = {
        "validation_id": "VAL-RCS-FRAME-VALID-001",
        "status": "pass",
        "stress_vectors_verified": 0,
        "governance_violations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    # 1. Existence Checks
    if not os.path.exists(registry_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing stress registry")
        return report

    if not os.path.exists(doc_path):
        report["status"] = "fail"
        report["governance_violations"].append("missing stress documentation")

    # 2. Registry Verification
    with open(registry_path, 'r') as f:
        registry = json.load(f)
        report["stress_vectors_verified"] = len(registry["stress_vectors"])
        
        # Check for mandatory invariants
        gov = registry["governance"]
        if gov["theorem_status"] != "NOT_PROVEN" or gov["scope_status"] != "STRICTLY_LOCAL_RESTRICTED_DOMAIN":
            report["status"] = "fail"
            report["governance_violations"].append("core governance invariants missing from registry")

    # 3. Result Verification
    if not os.path.exists(result_path):
         report["status"] = "warning"
         report["governance_violations"].append("stress audit results not yet generated by runner")
    else:
        with open(result_path, 'r') as f:
            data = json.load(f)
            if "quarantine_integrity_score" not in data:
                 report["status"] = "fail"
                 report["governance_violations"].append("invalid audit result format: quarantine_integrity_score missing")

    # 4. Doc Content Verification
    with open(doc_path, 'r') as f:
        content = f.read().lower()
        mandatory_terms = ["not_proven", "strictly_local_restricted_domain", "containment preservation doctrine", "epistemic stress validity"]
        for term in mandatory_terms:
            if term not in content:
                report["status"] = "fail"
                report["governance_violations"].append(f"missing mandatory governance term '{term}' in documentation")

    with open(val_out_path, 'w') as f:
        json.dump(report, f, indent=2)
        
    return report

if __name__ == "__main__":
    res = validate_containment_framework()
    print(json.dumps(res, indent=2))
