import json
from pathlib import Path
import pandas as pd

def analyze_cascade(run_id):
    root = Path(f'results/{run_id}/jobs')
    results = []
    
    for f in root.glob('**/summary.json'):
        try:
            d = json.load(open(f))
            # The summary structure for rd_sim_cpp seems to have 'final_metrics' or just top-level keys
            # Let's check the main.cpp report code: 
            # report[label] = { "active_area": m.active_area, ... }
            # Since label is generated by the wrapper, it might be in report["final"]
            # I'll search all keys for 'active_area'
            
            theta_g = d['config']['theta_g']
            seed = d['config']['seed']
            
            # Find active_area in the report
            active_area = 0
            for k, v in d.items():
                if isinstance(v, dict) and 'active_area' in v:
                    active_area = v['active_area']
                    break
            
            results.append({
                'theta_g': theta_g,
                'seed': seed,
                'active_area': active_area,
                'active_fraction': active_area / (128*128)
            })
        except Exception as e:
            print(f"Error analyzing {f}: {e}")
            
    if not results:
        print("No cascade results found.")
        return

    df = pd.DataFrame(results)
    df.to_csv(f'results/{run_id}/artifacts/cascade_data.csv', index=False)
    
    summary = df.groupby('theta_g')['active_fraction'].agg(['mean', 'std']).reset_index()
    summary.to_csv(f'results/{run_id}/artifacts/cascade_summary.csv', index=False)
    print("Cascade analysis complete. Summary:")
    print(summary)

if __name__ == '__main__':
    analyze_cascade('2026-05-17_run06_MT-LAW-A_TS4_2D_Cascade_Probe')
